### ISSUE TITLE
获取平台证书的序列号恒为‘0’，导致验签失败

### ISSUE THREAD

**Issue by don-du** [wechatpay-apiv3/wechatpay-guzzle-middleware#1]
方法: \WechatPay\GuzzleMiddleware\Auth\CertificateVerifier::parseSerialNo()

**Comment by tpirc3** [comment]
@dowle  你好，请提供一下PHP版本、系统类型与版本等相关信息，方便复现和定位问题

**Comment by tpirc3** [comment]
`parseSerialNo`代码与运行环境中openssl版本不兼容引发的问题，已修复：https://github.com/wechatpay-apiv3/wechatpay-guzzle-middleware/commit/118602bf759e8b1891719f856b0c189bf1ef63de ，感谢反馈！
