### ISSUE TITLE
PHP5.5下解密的问题

### ISSUE THREAD

**Issue by rundaisc** [wechatpay-apiv3/wechatpay-guzzle-middleware#19]
我看文档开始说明 可以基于`PHP5.5`。但是再解密的时候 需要使用`crypto_aead_aes256gcm_decrypt`，而在PHP5.5版本，只能安装`Sodium1.6`.... but .这个版本并不支持 `crypto_aead_aes256gcm_decrypt`。那么有什么方案可以替代吗，或者解决这个问题。有个 PHP5.5项目需要使用电商首付通。太尴尬了

**Comment by tpirc3** [comment]
PHP <= 5.6上使用aead_aes256gcm的⽅法：
安装libsodium扩展（1.X版本，2.X版本不⽀持PHP 5)
⾸先在系统上安装libsodium以及libsodium-dev (libsodium-devel)，然后`sudo pecl install -f libsodium-1.0.7`安装PHP扩展
