### ISSUE TITLE
Composer 包 是不是应该更新了

### ISSUE THREAD

**Issue by rundaisc** [wechatpay-apiv3/wechatpay-guzzle-middleware#20]
composer 跟 release 里面  0.1.1缺少 
MediaUtil.php
SensitiveInfoCrypto.php

**Comment by tpirc3** [comment]
已更新测试完成新特性，0.2.0版本已发布 [https://packagist.org/packages/wechatpay/wechatpay-guzzle-middleware#0.2.0](https://packagist.org/packages/wechatpay/wechatpay-guzzle-middleware#0.2.0)
