### ISSUE TITLE
分账动账通知

### ISSUE THREAD

**Issue by Maplejay** [wechatpay-apiv3/wechatpay-guzzle-middleware#27]
如何使用该sdk，解密这个接口的resource字段

**Comment by xy-peng** [comment]
请参考下[常见问题-证书和回调解密需要的AesGcm解密在哪里？](https://github.com/wechatpay-apiv3/wechatpay-guzzle-middleware#%E8%AF%81%E4%B9%A6%E5%92%8C%E5%9B%9E%E8%B0%83%E8%A7%A3%E5%AF%86%E9%9C%80%E8%A6%81%E7%9A%84aesgcm%E8%A7%A3%E5%AF%86%E5%9C%A8%E5%93%AA%E9%87%8C)
