### ISSUE TITLE
可否提高一下guzzleHttp组件的版本号？

### ISSUE THREAD

**Issue by Abbotton** [wechatpay-apiv3/wechatpay-guzzle-middleware#28]
rt.
在Laravel7.0中使用此组件，其他的扩展包会降级至低版本。

**Comment by tpirc3** [comment]
描述的意思是指在Laravel 7.0的PHP项目中使用wechatpay-guzzle-middleware会导致guzzlehttp相关扩展版本降低吗？
但是我看了下Laravel  7和wechatpay-guzzle-middleware依赖的guzzlehttp都是6.3版本，所以在一个项目同时用这两个包不会造成guzzlehttp版本降低的，建议再排查下是不是别的包引起的，如果还有问题麻烦再反馈

[https://packagist.org/packages/laravel/laravel](https://packagist.org/packages/laravel/laravel)
![image](https://user-images.githubusercontent.com/29061068/89763709-a400a500-db25-11ea-8bc8-df92604ab8b7.png)

[https://packagist.org/packages/wechatpay/wechatpay-guzzle-middleware](https://packagist.org/packages/wechatpay/wechatpay-guzzle-middleware)
![image](https://user-images.githubusercontent.com/29061068/89763771-c4306400-db25-11ea-87d5-e72c6d19438c.png)

**Comment by Abbotton** [comment]
非常感谢.我再看看.
