### ISSUE TITLE
通过api上传的图片 在微信服务商后台无法查看

### ISSUE THREAD

**Issue by ouyanghui-git** [wechatpay-apiv3/wechatpay-guzzle-middleware#29]
在提交入驻申请单的时候 上传门头照片和店内照片要求的是数组 下面图片分别是开发文档 以及代码块
![微信图片_20200822163942](https://user-images.githubusercontent.com/55080006/90952438-28dcae80-e496-11ea-8aee-b9eef79a8898.png)
![image](https://user-images.githubusercontent.com/55080006/90952484-79eca280-e496-11ea-9843-9cfbb9a599cb.png)
然后这是我在微信后台查看我上传的资料 发现图片显示不了 但是如果是当张上传的图片像身份证什么的 是可以正常查看的
![image](https://user-images.githubusercontent.com/55080006/90952509-abfe0480-e496-11ea-806e-1fa6a32e8b13.png)
![image](https://user-images.githubusercontent.com/55080006/90952519-c89a3c80-e496-11ea-83d5-04169a273cf4.png)
这是申请单编号 2000002152324883

**Comment by tpirc3** [comment]
社区里的同问题帖子已经给了初步结论，与商户平台有关，后续会在社区问题贴上继续跟进，这里的issue就先关闭了
https://developers.weixin.qq.com/community/pay/doc/000a002c1943e0a792dab1db65b800
