### ISSUE TITLE
支持协程吗

### ISSUE THREAD

**Issue by nine-city** [wechatpay-apiv3/wechatpay-guzzle-middleware#31]
比如swoole

**Comment by tpirc3** [comment]
wechatpay-guzzle-middleware是[Guzzle HttpClient](https://github.com/guzzle/guzzle)的中间件Middleware，所以只要能把Guzzle正常运行在基于Swoole的框架上，wechatpay-guzzle-middleware理论上就是能够正常使用的。

网上有一些方案能够让Guzzle运行在Swoole上，建议尝试下这些方案，把Guzzle在基于Swoole的框架上跑起来，然后再试一下wechatpay-guzzle-middleware是否可用，如果有兼容性问题，可以再反馈过来，我们看怎么支持到。

**Comment by nine-city** [comment]
感谢。我先试试。
