### ISSUE TITLE
composer 安装报错

### ISSUE THREAD

**Issue by yaoyingkang** [wechatpay-apiv3/wechatpay-guzzle-middleware#34]
Problem 1
    - Root composer.json requires PHP extension ext-csprng * but it is missing from your system. Install or enable PHP's csprng extension.

To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/7.3/php.ini
    - /usr/local/etc/php/7.3/conf.d/ext-opcache.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

csprng这个拓展貌似搜不到。。。。

**Comment by tpirc3** [comment]
csprng是PHP内置的扩展，应该会自动开启 https://www.php.net/manual/zh/book.csprng.php ，所以麻烦检查下服务器上的php编译参数有没有启用该扩展。
