### ISSUE TITLE
$stack = GuzzleHttp\HandlerStack::create();  这个类怎么都运行不起来

### ISSUE THREAD

**Issue by c88667220** [wechatpay-apiv3/wechatpay-guzzle-middleware#39]
$stack = GuzzleHttp\HandlerStack::create();
用官方的sdk 到这里就死了，根本不存在这个东西，是怎么回事啊？

**Comment by f2h2h1** [comment]
你需要先运行 `composer install`

**Comment by c88667220** [comment]
单独装 guzzlehttp ？

**Comment by c88667220** [comment]
可以了，确实要单独引入一个，你们咋不集成进去算了，还要额外下载  /哭笑

**Comment by xy-peng** [comment]
你是没有用包管理安装？ @c88667220

**Comment by tpirc3** [comment]
需要使用composer安装一下的
