### ISSUE TITLE
应答的微信支付签名验证失败

### ISSUE THREAD

**Issue by c88667220** [wechatpay-apiv3/wechatpay-guzzle-middleware#40]
应答的微信支付签名验证失败 但是有显示：prepay_id

**Comment by c88667220** [comment]
呼叫大神

**Comment by TheNorthMemory** [comment]
需要先下载平台证书，源码包内有个工具用来下载平台证书

**Comment by c88667220** [comment]
要用工具下载？这个不怎么人性化吧  我做三方平台的，那些用户不见得会下载这些东西，那意味着我得来个用户就要搞一遍这个？

**Comment by xy-peng** [comment]
是可以简化一点，java库实现了sdk内自动下载平台证书的

**Comment by f2h2h1** [comment]
可以运行这样一条命令来下载证书
```bash
php vendor/wechatpay/wechatpay-guzzle-middleware/tool/CertificateDownloader.php -k APIv3密钥 -m 商户号 -f 私钥路径 -s 商户API证书序列号 -o 下载平台证书的保存目录
```

**Comment by TheNorthMemory** [comment]
> 是可以简化一点，java库实现了sdk内自动下载平台证书的

在单体应用上，可以把下载平台证书做进类库逻辑里；不过，不建议这么做，分布式、多点负载的时候，这个下载逻辑其实就显得冗余了。建议是把下载证书单独做成服务，其他负载都只读使用，这样扩缩容就简单得多了（如容器及k8s scale replicas就可以用无状态deployment做了）

**Comment by xy-peng** [comment]
> 在单体应用上，可以把下载平台证书做进类库逻辑里；不过，不建议这么做，分布式、多点负载的时候，这个下载逻辑其实就显得冗余了。建议是把下载证书单独做成服务，其他负载都只读使用，这样扩缩容就简单得多了（如容器及k8s scale replicas就可以用无状态deployment做了）

说得没错。更建议把签名/验签/加密/解密的能力做成服务独立部署保护起来（注意不要单点保证可用性），不要把敏感的信息扩散到业务服务器上去了。

从实现上来说，java版的validator是初始化client时注册进去的，默认是本地证书版的😊 也可以选择自动获取证书的validator。甚至可以参考接口写一个新的validator做进去。

**Comment by c88667220** [comment]
> 可以运行这样一条命令来下载证书
> 
> ```shell
> php vendor/wechatpay/wechatpay-guzzle-middleware/tool/CertificateDownloader.php -k APIv3密钥 -m 商户号 -f 私钥路径 -s 商户API证书序列号 -o 下载平台证书的保存目录
> ```

感觉没有支付宝和钉钉那么简洁明了，他们那有个后台，直接都可以在线运行所有api接口，然后还可以生成代码几分钟就能全部搞好，而你们这一个简简单单的平台证书我搞一天了，一直提示我 NSS: client certificate not found (nickname not specified)，然后示例代码写的好乱，我还得自己重新做一遍

**Comment by c88667220** [comment]
我有个疑问，你们为毛要把PHP的这个做成命令行下载呢？直接集成到 sdk 不行？非得别人把你们这个重新搞一遍？

**Comment by c88667220** [comment]
反正我觉得这写的对于我们小白，太不友好了，大神们，赶紧改一下把  \抱拳

**Comment by zhimma** [comment]
我是用这个方法解决的
https://developers.weixin.qq.com/community/pay/doc/0006c092f10418281c5998b9256400
