### ISSUE TITLE
中间件为何要验证请求路径？

### ISSUE THREAD

**Issue by wuceyang** [wechatpay-apiv3/wechatpay-guzzle-middleware#44]
我在开发一个香港客户的商户管理平台。
在WechatPayMiddleware.php中，定义的
BASE_URLS为["/v3","/sandbox/v3/"],
API_DOMAINS定义为["api.mch.weixin.qq.com","api2.mch.weixin.qq.com"],
可是根据文档描述，境外还有个接入点的域名是https://apihk.mch.weixin.qq.com/hk/v3/这样的前缀，这样境外的域名(apihk.mch.weixin.qq.com)和请求路径(/hk/v3)校验都是通不过的。
这是说该中间件不适用于境外平台接入吗？还是说我手动添加这两个参数缺少的那部分就可以了？
目前结果是签名通过，但是商户进件提示接入模式错误

**Comment by xy-peng** [comment]
适合境外api的。只要是`api*.weixin.qq.com`的都可以用，欢迎pr。

**Comment by wuceyang** [comment]
那就要在配置中加入境外接入点的域名和/hk/v3的路径前缀，否则通不过
![image](https://user-images.githubusercontent.com/1538757/109948796-a0c54480-7d15-11eb-8a8e-863e10527910.png)

**Comment by tpirc3** [comment]
Fixed in #45

**Comment by tpirc3** [comment]
Released in [v0.2.2](https://packagist.org/packages/wechatpay/wechatpay-guzzle-middleware#0.2.2)
