### ISSUE TITLE
v3的开发库可以支持一下node吗

### ISSUE THREAD

**Issue by ooowennn** [wechatpay-apiv3/wechatpay-guzzle-middleware#47]

**Comment by xy-peng** [comment]
node有一些第三方的开源，可以参考下php的贡献者 TheNorthMemory 自己作品

 https://github.com/TheNorthMemory/wechatpay-axios-plugin

**Comment by ooowennn** [comment]
> node有一些第三方的开源，可以参考下php的贡献者 TheNorthMemory 自己作品
> 
> https://github.com/TheNorthMemory/wechatpay-axios-plugin

谢谢

**Comment by TheNorthMemory** [comment]
> node有一些第三方的开源，可以参考下php的贡献者 TheNorthMemory 自己作品
> 
> https://github.com/TheNorthMemory/wechatpay-axios-plugin

竟然不@我啊，我来自荐晚了么
