### ISSUE TITLE
应答的微信支付签名验证失败

### ISSUE THREAD

**Issue by cnjiangjun** [wechatpay-apiv3/wechatpay-guzzle-middleware#5]
从证书中获取的证书序列号与返回头中的序列号Wechatpay-Serial不一致，导致应答验签失败。

**Comment by cnjiangjun** [comment]
此处应使用平台证书而不是商户证书。

**Comment by biankemi** [comment]
@cnjiangjun 如何使用平台证书呢,中间件中是否有对应代码可参考

**Comment by cnjiangjun** [comment]
> @cnjiangjun 如何使用平台证书呢,中间件中是否有对应代码可参考

官方示例里面：
`$wechatpayMiddleware = WechatPay\GuzzleMiddleware\WechatPayMiddleware::builder()
        ->withMerchant($merchantId, $merchantSerialNumber, $merchantPrivateKey)
        ->withWechatPay($wechatpayCertificates) // 可传入多个微信支付平台证书，参数类型为array
        ->build();`
其中`$wechatpayCertificates`从微信下载并以一下类似方式加载：
`$wechatpayCertificates[] = WechatPay\GuzzleMiddleware\Util\PemUtil::loadCertificate($platformCertFolder . $platformCertFile);`

**Comment by cnjiangjun** [comment]
> @cnjiangjun 如何使用平台证书呢,中间件中是否有对应代码可参考

@biankemi 

官方示例里面：
`$wechatpayMiddleware = WechatPay\GuzzleMiddleware\WechatPayMiddleware::builder() ->withMerchant($merchantId, $merchantSerialNumber, $merchantPrivateKey) ->withWechatPay($wechatpayCertificates)->build();`
其中`$wechatpayCertificates`从微信下载并以以下类似方式加载即可：
`$wechatpayCertificates[] = WechatPay\GuzzleMiddleware\Util\PemUtil::loadCertificate($platformCertFolder . $platformCertFile);`
