### ISSUE TITLE
小程序调用支付api等功能的paySign需要手拼？

### ISSUE THREAD

**Issue by llllyang123** [wechatpay-apiv3/wechatpay-guzzle-middleware#50]
实例也没有，全靠摸索，和支付宝的文档差距好远。。。
看着文档简单，实际上复杂的都丢给了开发者

**Comment by xy-peng** [comment]
小程序的开发指引可以看这里[小程序支付开发指引](https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter2_8_2.shtml)

**Comment by xy-peng** [comment]
现阶段在开发者工具上确实不足，这个库的目标是提供基础的非业务的库供开发者参考。后面我们会分编程语言逐步推出包含业务api的库。
