### ISSUE TITLE
提案: 以guzzle7为底版，升级代码结构及驱动方式，并最低支持PHP7.2

### ISSUE THREAD

**Issue by TheNorthMemory** [wechatpay-apiv3/wechatpay-guzzle-middleware#51]
# 目标

- [x] 升级 guzzle 至 >= 7
- [x] 加入请求/返回数据类型签名功能
- [x] 重写一下敏感信息加解密的功能实现
- [x] 变更同步请求为异步请求，以 guzzle支持的 `[get|post|put|patch|delete]Async` 驱动
- [x] 代码变更为 `PromiseA+`风格
- [x] 动态方法型如 `v3->pay->transactions->native->postAsync()` 链式请求

**Comment by xy-peng** [comment]
对于异步请求和链式请求，能先给出一些代码片段，展示下开发者是如何使用它的吗？在贡献代码之前可以充分讨论讨论。

最好实现上使用的关键技术也介绍下？

**Comment by TheNorthMemory** [comment]
## 异步请求

网络编程是异步的，guzzle在5+就已经支持类似 `getAsync` 这样的 `PromiseA+` 实现，guzzle7 已经提权异步请求代码为 [ClientTrait](https://github.com/guzzle/guzzle/blob/master/src/ClientTrait.php)，可以像其他支持`Promise/A+`的开发语言一样，异步甚至协程式编程，请求的语法糖类似如下：

```php
$client->getAsync('v3/certificates', [])
  .then(function(ResponseInterface $response) {})
  .otherwise(function(ResponseInterface $response) {})
```

或者

```php
try {
  $response = $client->getAsync('v3/certificates', [])->wait();
} catch (Exception $e) {}
```

上述伪代码的核心思路是充分利用语法糖优势，把正常处理逻辑和异常处理逻辑区分开来，让语言自己解释自己。

## 链式调用

guzzle其实已经提供了链式型如 `get($uri, [])`语法糖，这里更进一步，就是把 `$uri` 也按照 `slash` 切分法，动态前置化，仅使HTTP Verbs保留 `\GuzzleHttp\RequestOptions`，工程化实践可见 [wechatpay-axios-plugin](https://github.com/TheNorthMemory/wechatpay-axios-plugin) 项目。

伪代码类似如下：

```php
$wxpay = new Wechatpay();

$wxpay->v3->certificates->get([]).then(function(){}).otherwise(function(){});

$res = $wxpay->v3->pay->transactions->native([])->wait();//native默认为`POST`
```

**Comment by TheNorthMemory** [comment]
merged onto the new repo: https://github.com/wechatpay-apiv3/wechatpay-php
