### ISSUE TITLE
是否有添加 test case 的计划？

### ISSUE THREAD

**Issue by tu6ge** [wechatpay-apiv3/wechatpay-guzzle-middleware#53]
如果没有，我愿意为项目做一些 test case

或者说，现在是不是有重构的计划，不适合现在做 test case

**Comment by xy-peng** [comment]
来得好不如来得巧，今天准备上新，是我们另外一位开发者贡献的。

**Comment by tu6ge** [comment]
好的

**Comment by xy-peng** [comment]
欢迎参与新的[wechatpay-php](https://github.com/wechatpay-apiv3/wechatpay-php) 😊
