### ISSUE TITLE
可否将 GuzzleHttp 的依赖提升至 ^7.0

### ISSUE THREAD

**Issue by feng-yifan** [wechatpay-apiv3/wechatpay-guzzle-middleware#54]
最新的 Laravel 8 对 GuzzleHttp 的依赖已经高过这个包的依赖了

![image](https://user-images.githubusercontent.com/15028843/125560640-d6feace0-326d-4ff1-913b-50593fa1aa03.png)

Laravel 8 会给出如下错误
``` bash
Call to undefined function GuzzleHttp\Psr7\hash() {"exception":"[object] (Error(code: 0): Call to undefined function GuzzleHttp\\Psr7\\hash() at /app/vendor/wechatpay/wechatpay-guzzle-middleware/src/Util/MediaUtil.php:91)
```

**Comment by feng-yifan** [comment]
@tpirc3

**Comment by feng-yifan** [comment]
目前手动将 Laravel 8 的 `guzzlehttp/guzzle` 依赖版本降级至 `^6.3` 作为临时方案了

**Comment by xy-peng** [comment]
直接迁移到 [wechatpay-php](https://github.com/wechatpay-apiv3/wechatpay-php) 呢？

**Comment by TheNorthMemory** [comment]
`Guzzle7`上，废弃了 `\GuzzleHttp\json_encode` 及 `\GuzzleHttp\Psr7\hash` 方法，分别被移动至 `\GuzzleHttp\Utils::jsonEncode` 及 `GuzzleHttp\Psr7\Utils::hash` 上，` Laravel 8+` 建议直接用 `wechatpay-php` 包，测试用例覆盖环境从`PHP7.2~8.0`都有github actions覆盖，可以顺畅使用。

**Comment by feng-yifan** [comment]
> 直接迁移到 [wechatpay-php](https://github.com/wechatpay-apiv3/wechatpay-php) 呢？

好的, 之前没有留意到有这个包

**Comment by feng-yifan** [comment]
> `Guzzle7`上，废弃了 `\GuzzleHttp\json_encode` 及 `\GuzzleHttp\Psr7\hash` 方法，分别被移动至 `\GuzzleHttp\Utils::jsonEncode` 及 `GuzzleHttp\Psr7\Utils::hash` 上，` Laravel 8+` 建议直接用 `wechatpay-php` 包，测试用例覆盖环境从`PHP7.2~8.0`都有github actions覆盖，可以顺畅使用。

多谢!
