### ISSUE TITLE
Call to undefined function GuzzleHttp\\Psr7\\hash()

### ISSUE THREAD

**Issue by diankemao** [wechatpay-apiv3/wechatpay-guzzle-middleware#55]
文件 WechatPay\GuzzleMiddleware\Util\MediaUtil.php
\GuzzleHttp\\Psr7\\hash() 找不到这个方法了，已废弃，修改成\GuzzleHttp\Psr7\Utils::hash()就ok了，请修复？

        $json = \GuzzleHttp\json_encode([
            'filename' => $basename,
            'sha256'   => \GuzzleHttp\Psr7\Utils::hash($stream, 'sha256'),
        ]);
        $this->meta = $json;

**Comment by diankemao** [comment]
把GuzzleHttp\Psr7\hash修改为\GuzzleHttp\Psr7\Utils::hash

**Comment by xy-peng** [comment]
新版本 guzzle 建议使用[wechatpay-php](https://github.com/wechatpay-apiv3/wechatpay-php)。
