### ISSUE TITLE
jsapi 公众号paySign的是怎么生成的？公众号支付拉取付款页面一直提示签名验证不过。 自己用签名验证工具验证是可以通过的

### ISSUE THREAD

**Issue by jk030611** [wechatpay-apiv3/wechatpay-guzzle-middleware#56]
public  function joinedByLineFeed($pieces)
    {
        return implode("\n", array_merge($pieces, array()));
    }
 public  function getSign($data)
    {
        $merchantPrivateKey = PemUtil::loadPrivateKey($this->config['apiclient_key_pem']);
        $signer = new PrivateKeySigner($this->config['serial_no'], $merchantPrivateKey);
        print_r($this->joinedByLineFeed($data));
        $message = $this->joinedByLineFeed($data);
        $result = $signer->sign($message);
        return $result->sign;
    }

 $time = time();
    $data['appId'] = $this->config['app_id'];//公众号appid
    $data['timeStamp'] = "$time";
    $data['nonceStr'] = $this->getRandChar(32);
    $data['package'] = 'prepay_id=' . $return['data']['prepay_id'];
    $data['paySign'] = $this->getSign($data);

**Comment by xy-peng** [comment]
建议使用我们新的 wechatpay-php，拉起支付的签名说明可以参考 [签名](https://github.com/wechatpay-apiv3/wechatpay-php#%E7%AD%BE%E5%90%8D)
