### ISSUE TITLE
请求回单下载链接时提示签名无效？

### ISSUE THREAD

**Issue by MingForce** [wechatpay-apiv3/wechatpay-guzzle-middleware#59]
https://pay.weixin.qq.com/docs/merchant/apis/batch-transfer-to-balance/download-receipt.html
通过微信支付API v3标准对通过查单获取到的download_url进行签名，并发起请求，即可下载到电子回单文件的数据流。参考右侧示例。

这个中间件的签名对下载回单不成功？不是自动签名的吗？为什么请求回单下载链接时提示签名无效
返回了{"code":"INVALID REQUEST","message":"错误的签名，导致验签失败"}

**Comment by MingForce** [comment]
我知道原因了，回单下载的签名和其他地方的签名不一样，没有body \n，要自己重写一下这个类，配置上就可以了。

**Comment by xy-peng** [comment]
@MingForce 建议使用 wechatpay-php
