### ISSUE TITLE
不适用于图片上传接口

### ISSUE THREAD

**Issue by MaiDouDuDuZai** [wechatpay-apiv3/wechatpay-guzzle-middleware#6]
调用[图片上传API](https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/tool/chapter3_1.shtml)时会提示签名错误，似乎是把整个body加入了待签名串。

**Comment by xy-peng** [comment]
是的，目前还不支持。

**Comment by browningweb** [comment]
只需要将 `WechatPay2Credentials` 中的 `buildMessage` 方法修改一下就可以了。

protected function buildMessage($nonce, $timestamp, RequestInterface $request)
    {
        $body = '';
        if ($request->hasHeader('metaJson')) {
            $body = $request->getHeaderLine('metaJson');
        } else {
            $bodyStream = $request->getBody();
            // TODO: handle non-seekable stream
            if ($bodyStream->isSeekable()) {
                $body = (string)$bodyStream;
                $bodyStream->rewind();
            }
        }
        return $request->getMethod()."\n".
            $request->getRequestTarget()."\n".
            $timestamp."\n".
            $nonce."\n".
            $body."\n";
    }

**Comment by TheNorthMemory** [comment]
不增加其它入参情况下，仅使用标准 `Guzzle` 包实现媒体文件上传 https://github.com/TheNorthMemory/wechatpay-guzzle-middleware/commit/2c975ba4edf3c1613b9588b7efde9b2d361cba24

核心是使用 `GuzzleHttp\Psr7\FnStream`（通过  `__toString`) 构造出 签名所需 `meta` JSON串，通过 `getSize` 返回值，强制使 `GuzzleHttp\Handler\CurlFactory::applyBody` 走 `CURLOPT_UPLOAD` 逻辑, 通过 `$request->getBody()`  获取 `GuzzleHttp\Psr7\MultipartStream` 流内容。
