### ISSUE TITLE
请问 能不能给我 post的例子

### ISSUE THREAD

**Issue by xibusuper** [wechatpay-apiv3/wechatpay-guzzle-middleware#7]
请问能不能给个 post 的例子  我看了 guzzle 官方文档 尝试了很多方法 返回都是   

Client error: `POST https://api.mch.weixin.qq.com/v3/applyment4sub/applyment/` resulted in a `400 Bad Request` response

不知道什么原因

**Comment by tpirc3** [comment]
Guzzle发起POST请求可以看官方文档的[这里](https://guzzle-cn.readthedocs.io/zh_CN/latest/quickstart.html#id9)，使用 `json` / `body`等参数

结合到WechatPay的API，使用示例如下：
```php
$resp = $client->request('POST', 'https://api.mch.weixin.qq.com/v3/...', [
    'json' => [ // JSON请求体
        'field1' => 'value1',
        'field2' => 'value2'
    ],
    'headers' => [ 'Accept' => 'application/json' ]
]);
```
对于`400 Bad Request`可能是参数缺失/类型不对等错误，可以看下响应body里具体的错误提示
