### ISSUE TITLE
能不能有一些详细的demo

### ISSUE THREAD

**Issue by c4ys** [wechatpay-apiv3/wechatpay-guzzle-middleware#9]
README的例子太差了：

merchantSerialNumber 哪里来的，获取平台证书接口下载来的serial_no还是微信后台证书的serial_no，我不知道，只能都尝试一遍，全靠猜。

没有好的例子，浪费大家时间，这是微信支付官方推荐的库吗？

**Comment by tpirc3** [comment]
关于商户API证书和微信支付平台证书的相关说明可以看[API V3文档的介绍](https://wechatpay-api.gitbook.io/wechatpay-api-v3/ren-zheng/zheng-shu)
README.md中示例的各字段的中文含义已补充注释了，可以再看下

证书相关的问题/疑问也欢迎在[开发者社区](https://developers.weixin.qq.com/community/pay)里进行讨论。
